// flow-typed signature: 100338d8362fb9f46ae34a66374249ed
// flow-typed version: <<STUB>>/ejs-loader_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ejs-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ejs-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ejs-loader/index' {
  declare module.exports: $Exports<'ejs-loader'>;
}
declare module 'ejs-loader/index.js' {
  declare module.exports: $Exports<'ejs-loader'>;
}
