// flow-typed signature: 92c6b6ed1d1150f8f0cf2c2e41cc53b3
// flow-typed version: <<STUB>>/webpack-module-hot-accept_v^1.0.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-module-hot-accept'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-module-hot-accept' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-module-hot-accept/index' {
  declare module.exports: $Exports<'webpack-module-hot-accept'>;
}
declare module 'webpack-module-hot-accept/index.js' {
  declare module.exports: $Exports<'webpack-module-hot-accept'>;
}
